browser=chrome
environment=qa
url=https://www.saucedemo.com/
username=standard_user
password=secret_sauce
timeout=30
headless=false;

qa.url=https://www.saucedemo.com
uat.url=https://uat-app.com
prod.url=https://prod-app.com
